# custom property (
file:
    directory: D:/GSY/download/greengram_ver1

# mybatis setting
mybatis:
    mapper-locations: xml/**/*.xml

# Base URL setting
#server:
#   servlet:
#      context-path: /api

spring:
    application:
        name: GreenGramVer1

    servlet:
      multipart:
          max-file-size: 10MB

    #DB setting
    datasource:
        url: jdbc:mariadb://localhost/greengram_ver1
        username: root
        password: green502
#swagger설정
springdoc:
    swagger-ui:
        default-model-expand-depth: 10
        display-request-duration: true
        operations-sorter: method
        path: /swagger
    cache:
        disabled: true